# Generated by Django 4.2.30 on 2026-06-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=50)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorCursoAsignatura',
            fields=[
                ('id_pca', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profesor_curso_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=13)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=2, null=True)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id_colegio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colegio', models.CharField(max_length=100)),
                ('nit', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_institucional', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=7)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota_aprobacion', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'colegio',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.OneToOneField(db_column='id_profesor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='academico.usuario')),
                ('titulo_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia_anios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
    ]
