# Generated by Django 4.2.30 on 2026-06-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colegio',
            options={'managed': False},
        ),
    ]
